# Generated by Django 3.1.5 on 2021-03-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Import_CSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_id', models.TextField(verbose_name='Lab ID')),
                ('amostra_reference', models.CharField(max_length=200, verbose_name='Amostra Reference')),
                ('resultado_class', models.CharField(max_length=75, verbose_name='Resultado Class')),
                ('results_type', models.IntegerField(verbose_name='Results Type')),
                ('lab_name', models.CharField(max_length=75, verbose_name='Lab Name')),
                ('subspecies', models.CharField(max_length=100, verbose_name='Subspecies')),
                ('st', models.CharField(max_length=50, verbose_name='ST')),
                ('foco_id_old', models.CharField(max_length=200, verbose_name='Foco ID Old')),
                ('foco_id_new', models.CharField(max_length=200, verbose_name='Foco ID New')),
                ('notes', models.TextField(verbose_name='Notes')),
                ('sample_sent_date', models.DateField(verbose_name='Sample Sent Date')),
                ('lab_results_date', models.DateField(verbose_name='Lab Results Date')),
            ],
        ),
    ]
