# Generated by Django 3.1.5 on 2021-03-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import_csv',
            name='lab_results_date',
            field=models.CharField(max_length=10, verbose_name='Lab Results Date'),
        ),
        migrations.AlterField(
            model_name='import_csv',
            name='sample_sent_date',
            field=models.CharField(max_length=10, verbose_name='Sample Sent Date'),
        ),
    ]
