# Generated by Django 3.1.5 on 2021-03-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210306_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import_csv',
            name='lab_results_date',
            field=models.TextField(verbose_name='Lab Results Date'),
        ),
        migrations.AlterField(
            model_name='import_csv',
            name='sample_sent_date',
            field=models.TextField(verbose_name='Sample Sent Date'),
        ),
    ]
