# Generated by Django 3.1.5 on 2021-03-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210306_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import_csv',
            name='results_type',
            field=models.IntegerField(null=True, verbose_name='Results Type'),
        ),
    ]
