# Generated by Django 3.1.7 on 2021-03-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210317_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import_csv',
            name='results_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='Results Type'),
        ),
    ]
