# Generated by Django 3.1.7 on 2021-03-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_lab_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='lab_resultsAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
