# Generated by Django 3.1.7 on 2021-03-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210318_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import_csv',
            name='resultado_class',
            field=models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo'), ('REJEITADA', 'Rejeitava'), ('INCONCLUSIVO', 'Inconclusivo'), ('NÃO EFETUADA', 'Nao Efetuada')], default='POSITIVO', max_length=75, verbose_name='Resultado Class'),
        ),
    ]
